# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lsriw/Documents/Camugli/hsvs/vp/vp.srcs/sources_1/ip/LUT/LUT.xci
# IP: The module: 'LUT' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lsriw/Documents/Camugli/hsvs/vp/vp.srcs/sources_1/ip/LUT/LUT_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'LUT'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/lsriw/Documents/Camugli/hsvs/vp/vp.srcs/sources_1/ip/LUT/LUT.xci
# IP: The module: 'LUT' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lsriw/Documents/Camugli/hsvs/vp/vp.srcs/sources_1/ip/LUT/LUT_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'LUT'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
