# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lsriw/Desktop/klara/hsvs1/hsvs/tlr/tlr/tlr.srcs/sources_1/ip/median5x5_1/median5x5_1.xci
# IP: The module: 'median5x5_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/lsriw/Desktop/klara/hsvs1/hsvs/tlr/tlr/tlr.srcs/sources_1/ip/median5x5_1/sources_1/ip/delayLineBRAM/delayLineBRAM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==delayLineBRAM || ORIG_REF_NAME==delayLineBRAM} -quiet] -quiet

# XDC: /home/lsriw/Desktop/klara/hsvs1/hsvs/tlr/tlr/tlr.srcs/sources_1/ip/median5x5_1/sources_1/ip/delayLineBRAM/delayLineBRAM_ooc.xdc

# IP: /home/lsriw/Desktop/klara/hsvs1/hsvs/tlr/tlr/tlr.srcs/sources_1/ip/median5x5_1/median5x5_1.xci
# IP: The module: 'median5x5_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/lsriw/Desktop/klara/hsvs1/hsvs/tlr/tlr/tlr.srcs/sources_1/ip/median5x5_1/sources_1/ip/delayLineBRAM/delayLineBRAM.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==delayLineBRAM || ORIG_REF_NAME==delayLineBRAM} -quiet] -quiet

# XDC: /home/lsriw/Desktop/klara/hsvs1/hsvs/tlr/tlr/tlr.srcs/sources_1/ip/median5x5_1/sources_1/ip/delayLineBRAM/delayLineBRAM_ooc.xdc
