# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lsriw/Desktop/klara/hsvs1/hsvs/tlr/tlr/tlr.srcs/sources_1/bd/tsr/ip/tsr_median5x5_0_0/tsr_median5x5_0_0.xci
# IP: The module: 'tsr_median5x5_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/lsriw/Desktop/klara/hsvs1/hsvs/tlr/tlr/tlr.srcs/sources_1/bd/tsr/ip/tsr_median5x5_0_0/sources_1/ip/delayLineBRAM/delayLineBRAM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==delayLineBRAM || ORIG_REF_NAME==delayLineBRAM} -quiet] -quiet

# XDC: /home/lsriw/Desktop/klara/hsvs1/hsvs/tlr/tlr/tlr.srcs/sources_1/bd/tsr/ip/tsr_median5x5_0_0/sources_1/ip/delayLineBRAM/delayLineBRAM_ooc.xdc

# IP: /home/lsriw/Desktop/klara/hsvs1/hsvs/tlr/tlr/tlr.srcs/sources_1/bd/tsr/ip/tsr_median5x5_0_0/tsr_median5x5_0_0.xci
# IP: The module: 'tsr_median5x5_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/lsriw/Desktop/klara/hsvs1/hsvs/tlr/tlr/tlr.srcs/sources_1/bd/tsr/ip/tsr_median5x5_0_0/sources_1/ip/delayLineBRAM/delayLineBRAM.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==delayLineBRAM || ORIG_REF_NAME==delayLineBRAM} -quiet] -quiet

# XDC: /home/lsriw/Desktop/klara/hsvs1/hsvs/tlr/tlr/tlr.srcs/sources_1/bd/tsr/ip/tsr_median5x5_0_0/sources_1/ip/delayLineBRAM/delayLineBRAM_ooc.xdc
