# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/hdmi_vga_zybo_src/Zybo_HDMI.xdc

# Block Designs: bd/tsr/tsr.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tsr || ORIG_REF_NAME==tsr} -quiet] -quiet

# IP: bd/tsr/ip/tsr_processing_system7_0_0/tsr_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tsr_processing_system7_0_0 || ORIG_REF_NAME==tsr_processing_system7_0_0} -quiet] -quiet

# IP: bd/tsr/ip/tsr_dvi2rgb_0_0/tsr_dvi2rgb_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tsr_dvi2rgb_0_0 || ORIG_REF_NAME==tsr_dvi2rgb_0_0} -quiet] -quiet

# IP: bd/tsr/ip/tsr_rgb2vga_0_0/tsr_rgb2vga_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tsr_rgb2vga_0_0 || ORIG_REF_NAME==tsr_rgb2vga_0_0} -quiet] -quiet

# IP: bd/tsr/ip/tsr_clk_wiz_0_0/tsr_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tsr_clk_wiz_0_0 || ORIG_REF_NAME==tsr_clk_wiz_0_0} -quiet] -quiet

# IP: bd/tsr/ip/tsr_xlconstant_0_0/tsr_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tsr_xlconstant_0_0 || ORIG_REF_NAME==tsr_xlconstant_0_0} -quiet] -quiet

# IP: bd/tsr/ip/tsr_xlconstant_1_0/tsr_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tsr_xlconstant_1_0 || ORIG_REF_NAME==tsr_xlconstant_1_0} -quiet] -quiet

# IP: bd/tsr/ip/tsr_parameter_register_0_0/tsr_parameter_register_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tsr_parameter_register_0_0 || ORIG_REF_NAME==tsr_parameter_register_0_0} -quiet] -quiet

# IP: bd/tsr/ip/tsr_segmentation_0_0/tsr_segmentation_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tsr_segmentation_0_0 || ORIG_REF_NAME==tsr_segmentation_0_0} -quiet] -quiet

# IP: bd/tsr/ip/tsr_video_mux_0_0/tsr_video_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tsr_video_mux_0_0 || ORIG_REF_NAME==tsr_video_mux_0_0} -quiet] -quiet

# IP: bd/tsr/ip/tsr_ps7_0_axi_periph_0/tsr_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tsr_ps7_0_axi_periph_0 || ORIG_REF_NAME==tsr_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/tsr/ip/tsr_rst_ps7_0_100M_0/tsr_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tsr_rst_ps7_0_100M_0 || ORIG_REF_NAME==tsr_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/tsr/ip/tsr_median5x5_0_0/tsr_median5x5_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tsr_median5x5_0_0 || ORIG_REF_NAME==tsr_median5x5_0_0} -quiet] -quiet

# IP: bd/tsr/ip/tsr_auto_pc_0/tsr_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tsr_auto_pc_0 || ORIG_REF_NAME==tsr_auto_pc_0} -quiet] -quiet

# XDC: bd/tsr/tsr_ooc.xdc
